<?php
/**
 * ItineraryResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Abulia\TflUnified\Swagger
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Abulia\TflUnified\Swagger\Model;

use \ArrayAccess;
use Illuminate\Contracts\Support\Jsonable;

/**
 * ItineraryResult Class Doc Comment
 *
 * @category    Class
 * @description A DTO representing a list of possible journeys.
 * @package     Abulia\TflUnified\Swagger
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ItineraryResult implements ArrayAccess, Jsonable
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ItineraryResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'cycle_hire_docking_station_data' => '\Abulia\TflUnified\Swagger\Model\JourneyPlannerCycleHireDockingStationData',
        'journey_vector' => '\Abulia\TflUnified\Swagger\Model\JourneyVector',
        'journeys' => '\Abulia\TflUnified\Swagger\Model\Journey[]',
        'lines' => '\Abulia\TflUnified\Swagger\Model\Line[]',
        'recommended_max_age_minutes' => 'int',
        'search_criteria' => '\Abulia\TflUnified\Swagger\Model\SearchCriteria',
        'stop_messages' => 'string[]'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'cycle_hire_docking_station_data' => 'cycleHireDockingStationData',
        'journey_vector' => 'journeyVector',
        'journeys' => 'journeys',
        'lines' => 'lines',
        'recommended_max_age_minutes' => 'recommendedMaxAgeMinutes',
        'search_criteria' => 'searchCriteria',
        'stop_messages' => 'stopMessages'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'cycle_hire_docking_station_data' => 'setCycleHireDockingStationData',
        'journey_vector' => 'setJourneyVector',
        'journeys' => 'setJourneys',
        'lines' => 'setLines',
        'recommended_max_age_minutes' => 'setRecommendedMaxAgeMinutes',
        'search_criteria' => 'setSearchCriteria',
        'stop_messages' => 'setStopMessages'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'cycle_hire_docking_station_data' => 'getCycleHireDockingStationData',
        'journey_vector' => 'getJourneyVector',
        'journeys' => 'getJourneys',
        'lines' => 'getLines',
        'recommended_max_age_minutes' => 'getRecommendedMaxAgeMinutes',
        'search_criteria' => 'getSearchCriteria',
        'stop_messages' => 'getStopMessages'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cycle_hire_docking_station_data'] = isset($data['cycle_hire_docking_station_data']) ? $data['cycle_hire_docking_station_data'] : null;
        $this->container['journey_vector'] = isset($data['journey_vector']) ? $data['journey_vector'] : null;
        $this->container['journeys'] = isset($data['journeys']) ? $data['journeys'] : null;
        $this->container['lines'] = isset($data['lines']) ? $data['lines'] : null;
        $this->container['recommended_max_age_minutes'] = isset($data['recommended_max_age_minutes']) ? $data['recommended_max_age_minutes'] : null;
        $this->container['search_criteria'] = isset($data['search_criteria']) ? $data['search_criteria'] : null;
        $this->container['stop_messages'] = isset($data['stop_messages']) ? $data['stop_messages'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets cycle_hire_docking_station_data
     * @return \Abulia\TflUnified\Swagger\Model\JourneyPlannerCycleHireDockingStationData
     */
    public function getCycleHireDockingStationData()
    {
        return $this->container['cycle_hire_docking_station_data'];
    }

    /**
     * Sets cycle_hire_docking_station_data
     * @param \Abulia\TflUnified\Swagger\Model\JourneyPlannerCycleHireDockingStationData $cycle_hire_docking_station_data
     * @return $this
     */
    public function setCycleHireDockingStationData($cycle_hire_docking_station_data)
    {
        $this->container['cycle_hire_docking_station_data'] = $cycle_hire_docking_station_data;

        return $this;
    }

    /**
     * Gets journey_vector
     * @return \Abulia\TflUnified\Swagger\Model\JourneyVector
     */
    public function getJourneyVector()
    {
        return $this->container['journey_vector'];
    }

    /**
     * Sets journey_vector
     * @param \Abulia\TflUnified\Swagger\Model\JourneyVector $journey_vector
     * @return $this
     */
    public function setJourneyVector($journey_vector)
    {
        $this->container['journey_vector'] = $journey_vector;

        return $this;
    }

    /**
     * Gets journeys
     * @return \Abulia\TflUnified\Swagger\Model\Journey[]
     */
    public function getJourneys()
    {
        return $this->container['journeys'];
    }

    /**
     * Sets journeys
     * @param \Abulia\TflUnified\Swagger\Model\Journey[] $journeys
     * @return $this
     */
    public function setJourneys($journeys)
    {
        $this->container['journeys'] = $journeys;

        return $this;
    }

    /**
     * Gets lines
     * @return \Abulia\TflUnified\Swagger\Model\Line[]
     */
    public function getLines()
    {
        return $this->container['lines'];
    }

    /**
     * Sets lines
     * @param \Abulia\TflUnified\Swagger\Model\Line[] $lines
     * @return $this
     */
    public function setLines($lines)
    {
        $this->container['lines'] = $lines;

        return $this;
    }

    /**
     * Gets recommended_max_age_minutes
     * @return int
     */
    public function getRecommendedMaxAgeMinutes()
    {
        return $this->container['recommended_max_age_minutes'];
    }

    /**
     * Sets recommended_max_age_minutes
     * @param int $recommended_max_age_minutes
     * @return $this
     */
    public function setRecommendedMaxAgeMinutes($recommended_max_age_minutes)
    {
        $this->container['recommended_max_age_minutes'] = $recommended_max_age_minutes;

        return $this;
    }

    /**
     * Gets search_criteria
     * @return \Abulia\TflUnified\Swagger\Model\SearchCriteria
     */
    public function getSearchCriteria()
    {
        return $this->container['search_criteria'];
    }

    /**
     * Sets search_criteria
     * @param \Abulia\TflUnified\Swagger\Model\SearchCriteria $search_criteria
     * @return $this
     */
    public function setSearchCriteria($search_criteria)
    {
        $this->container['search_criteria'] = $search_criteria;

        return $this;
    }

    /**
     * Gets stop_messages
     * @return string[]
     */
    public function getStopMessages()
    {
        return $this->container['stop_messages'];
    }

    /**
     * Sets stop_messages
     * @param string[] $stop_messages
     * @return $this
     */
    public function setStopMessages($stop_messages)
    {
        $this->container['stop_messages'] = $stop_messages;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * To allow implict conversion to JSON by Laravel.
     */
    public function toJson($options = 0)
    {
        return $this->__toString();
    }

    /**
     * For convenient property based access.
     */
    public function __get($name)
    {
        if (isset(static::$getters[$name])) {
            return $this->{static::$getters[$name]}();
        }
        return null;
    }
}


