<?php
/**
 * LineGroup
 *
 * PHP version 5
 *
 * @category Class
 * @package  Abulia\TflUnified\Swagger
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Abulia\TflUnified\Swagger\Model;

use \ArrayAccess;
use Illuminate\Contracts\Support\Jsonable;

/**
 * LineGroup Class Doc Comment
 *
 * @category    Class
 * @package     Abulia\TflUnified\Swagger
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LineGroup implements ArrayAccess, Jsonable
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'LineGroup';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'line_identifier' => 'string[]',
        'naptan_id_reference' => 'string',
        'station_atco_code' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'line_identifier' => 'lineIdentifier',
        'naptan_id_reference' => 'naptanIdReference',
        'station_atco_code' => 'stationAtcoCode'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'line_identifier' => 'setLineIdentifier',
        'naptan_id_reference' => 'setNaptanIdReference',
        'station_atco_code' => 'setStationAtcoCode'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'line_identifier' => 'getLineIdentifier',
        'naptan_id_reference' => 'getNaptanIdReference',
        'station_atco_code' => 'getStationAtcoCode'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['line_identifier'] = isset($data['line_identifier']) ? $data['line_identifier'] : null;
        $this->container['naptan_id_reference'] = isset($data['naptan_id_reference']) ? $data['naptan_id_reference'] : null;
        $this->container['station_atco_code'] = isset($data['station_atco_code']) ? $data['station_atco_code'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets line_identifier
     * @return string[]
     */
    public function getLineIdentifier()
    {
        return $this->container['line_identifier'];
    }

    /**
     * Sets line_identifier
     * @param string[] $line_identifier
     * @return $this
     */
    public function setLineIdentifier($line_identifier)
    {
        $this->container['line_identifier'] = $line_identifier;

        return $this;
    }

    /**
     * Gets naptan_id_reference
     * @return string
     */
    public function getNaptanIdReference()
    {
        return $this->container['naptan_id_reference'];
    }

    /**
     * Sets naptan_id_reference
     * @param string $naptan_id_reference
     * @return $this
     */
    public function setNaptanIdReference($naptan_id_reference)
    {
        $this->container['naptan_id_reference'] = $naptan_id_reference;

        return $this;
    }

    /**
     * Gets station_atco_code
     * @return string
     */
    public function getStationAtcoCode()
    {
        return $this->container['station_atco_code'];
    }

    /**
     * Sets station_atco_code
     * @param string $station_atco_code
     * @return $this
     */
    public function setStationAtcoCode($station_atco_code)
    {
        $this->container['station_atco_code'] = $station_atco_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * To allow implict conversion to JSON by Laravel.
     */
    public function toJson($options = 0)
    {
        return $this->__toString();
    }

    /**
     * For convenient property based access.
     */
    public function __get($name)
    {
        if (isset(static::$getters[$name])) {
            return $this->{static::$getters[$name]}();
        }
        return null;
    }
}


