<?php
/**
 * RouteSequence
 *
 * PHP version 5
 *
 * @category Class
 * @package  Abulia\TflUnified\Swagger
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Abulia\TflUnified\Swagger\Model;

use \ArrayAccess;
use Illuminate\Contracts\Support\Jsonable;

/**
 * RouteSequence Class Doc Comment
 *
 * @category    Class
 * @package     Abulia\TflUnified\Swagger
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RouteSequence implements ArrayAccess, Jsonable
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RouteSequence';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'direction' => 'string',
        'is_outbound_only' => 'bool',
        'line_id' => 'string',
        'line_name' => 'string',
        'line_strings' => 'string[]',
        'mode' => 'string',
        'ordered_line_routes' => '\Abulia\TflUnified\Swagger\Model\OrderedRoute[]',
        'stations' => '\Abulia\TflUnified\Swagger\Model\MatchedStop[]',
        'stop_point_sequences' => '\Abulia\TflUnified\Swagger\Model\StopPointSequence[]'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'direction' => 'direction',
        'is_outbound_only' => 'isOutboundOnly',
        'line_id' => 'lineId',
        'line_name' => 'lineName',
        'line_strings' => 'lineStrings',
        'mode' => 'mode',
        'ordered_line_routes' => 'orderedLineRoutes',
        'stations' => 'stations',
        'stop_point_sequences' => 'stopPointSequences'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'direction' => 'setDirection',
        'is_outbound_only' => 'setIsOutboundOnly',
        'line_id' => 'setLineId',
        'line_name' => 'setLineName',
        'line_strings' => 'setLineStrings',
        'mode' => 'setMode',
        'ordered_line_routes' => 'setOrderedLineRoutes',
        'stations' => 'setStations',
        'stop_point_sequences' => 'setStopPointSequences'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'direction' => 'getDirection',
        'is_outbound_only' => 'getIsOutboundOnly',
        'line_id' => 'getLineId',
        'line_name' => 'getLineName',
        'line_strings' => 'getLineStrings',
        'mode' => 'getMode',
        'ordered_line_routes' => 'getOrderedLineRoutes',
        'stations' => 'getStations',
        'stop_point_sequences' => 'getStopPointSequences'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['direction'] = isset($data['direction']) ? $data['direction'] : null;
        $this->container['is_outbound_only'] = isset($data['is_outbound_only']) ? $data['is_outbound_only'] : null;
        $this->container['line_id'] = isset($data['line_id']) ? $data['line_id'] : null;
        $this->container['line_name'] = isset($data['line_name']) ? $data['line_name'] : null;
        $this->container['line_strings'] = isset($data['line_strings']) ? $data['line_strings'] : null;
        $this->container['mode'] = isset($data['mode']) ? $data['mode'] : null;
        $this->container['ordered_line_routes'] = isset($data['ordered_line_routes']) ? $data['ordered_line_routes'] : null;
        $this->container['stations'] = isset($data['stations']) ? $data['stations'] : null;
        $this->container['stop_point_sequences'] = isset($data['stop_point_sequences']) ? $data['stop_point_sequences'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets direction
     * @return string
     */
    public function getDirection()
    {
        return $this->container['direction'];
    }

    /**
     * Sets direction
     * @param string $direction
     * @return $this
     */
    public function setDirection($direction)
    {
        $this->container['direction'] = $direction;

        return $this;
    }

    /**
     * Gets is_outbound_only
     * @return bool
     */
    public function getIsOutboundOnly()
    {
        return $this->container['is_outbound_only'];
    }

    /**
     * Sets is_outbound_only
     * @param bool $is_outbound_only
     * @return $this
     */
    public function setIsOutboundOnly($is_outbound_only)
    {
        $this->container['is_outbound_only'] = $is_outbound_only;

        return $this;
    }

    /**
     * Gets line_id
     * @return string
     */
    public function getLineId()
    {
        return $this->container['line_id'];
    }

    /**
     * Sets line_id
     * @param string $line_id
     * @return $this
     */
    public function setLineId($line_id)
    {
        $this->container['line_id'] = $line_id;

        return $this;
    }

    /**
     * Gets line_name
     * @return string
     */
    public function getLineName()
    {
        return $this->container['line_name'];
    }

    /**
     * Sets line_name
     * @param string $line_name
     * @return $this
     */
    public function setLineName($line_name)
    {
        $this->container['line_name'] = $line_name;

        return $this;
    }

    /**
     * Gets line_strings
     * @return string[]
     */
    public function getLineStrings()
    {
        return $this->container['line_strings'];
    }

    /**
     * Sets line_strings
     * @param string[] $line_strings
     * @return $this
     */
    public function setLineStrings($line_strings)
    {
        $this->container['line_strings'] = $line_strings;

        return $this;
    }

    /**
     * Gets mode
     * @return string
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     * @param string $mode
     * @return $this
     */
    public function setMode($mode)
    {
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets ordered_line_routes
     * @return \Abulia\TflUnified\Swagger\Model\OrderedRoute[]
     */
    public function getOrderedLineRoutes()
    {
        return $this->container['ordered_line_routes'];
    }

    /**
     * Sets ordered_line_routes
     * @param \Abulia\TflUnified\Swagger\Model\OrderedRoute[] $ordered_line_routes
     * @return $this
     */
    public function setOrderedLineRoutes($ordered_line_routes)
    {
        $this->container['ordered_line_routes'] = $ordered_line_routes;

        return $this;
    }

    /**
     * Gets stations
     * @return \Abulia\TflUnified\Swagger\Model\MatchedStop[]
     */
    public function getStations()
    {
        return $this->container['stations'];
    }

    /**
     * Sets stations
     * @param \Abulia\TflUnified\Swagger\Model\MatchedStop[] $stations
     * @return $this
     */
    public function setStations($stations)
    {
        $this->container['stations'] = $stations;

        return $this;
    }

    /**
     * Gets stop_point_sequences
     * @return \Abulia\TflUnified\Swagger\Model\StopPointSequence[]
     */
    public function getStopPointSequences()
    {
        return $this->container['stop_point_sequences'];
    }

    /**
     * Sets stop_point_sequences
     * @param \Abulia\TflUnified\Swagger\Model\StopPointSequence[] $stop_point_sequences
     * @return $this
     */
    public function setStopPointSequences($stop_point_sequences)
    {
        $this->container['stop_point_sequences'] = $stop_point_sequences;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * To allow implict conversion to JSON by Laravel.
     */
    public function toJson($options = 0)
    {
        return $this->__toString();
    }

    /**
     * For convenient property based access.
     */
    public function __get($name)
    {
        if (isset(static::$getters[$name])) {
            return $this->{static::$getters[$name]}();
        }
        return null;
    }
}


