<?php
/**
 * StopPoint
 *
 * PHP version 5
 *
 * @category Class
 * @package  Abulia\TflUnified\Swagger
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Abulia\TflUnified\Swagger\Model;

use \ArrayAccess;
use Illuminate\Contracts\Support\Jsonable;

/**
 * StopPoint Class Doc Comment
 *
 * @category    Class
 * @package     Abulia\TflUnified\Swagger
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StopPoint implements ArrayAccess, Jsonable
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'StopPoint';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'accessibility_summary' => 'string',
        'additional_properties' => '\Abulia\TflUnified\Swagger\Model\AdditionalProperties[]',
        'children' => '\Abulia\TflUnified\Swagger\Model\Place[]',
        'children_urls' => 'string[]',
        'common_name' => 'string',
        'distance' => 'double',
        'full_name' => 'string',
        'hub_naptan_code' => 'string',
        'ics_code' => 'string',
        'id' => 'string',
        'indicator' => 'string',
        'lat' => 'double',
        'line_group' => '\Abulia\TflUnified\Swagger\Model\LineGroup[]',
        'line_mode_groups' => '\Abulia\TflUnified\Swagger\Model\LineModeGroup[]',
        'lines' => '\Abulia\TflUnified\Swagger\Model\Identifier[]',
        'lon' => 'double',
        'modes' => 'string[]',
        'naptan_id' => 'string',
        'naptan_mode' => 'string',
        'place_type' => 'string',
        'platform_name' => 'string',
        'sms_code' => 'string',
        'station_naptan' => 'string',
        'status' => 'bool',
        'stop_letter' => 'string',
        'stop_type' => 'string',
        'url' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'accessibility_summary' => 'accessibilitySummary',
        'additional_properties' => 'additionalProperties',
        'children' => 'children',
        'children_urls' => 'childrenUrls',
        'common_name' => 'commonName',
        'distance' => 'distance',
        'full_name' => 'fullName',
        'hub_naptan_code' => 'hubNaptanCode',
        'ics_code' => 'icsCode',
        'id' => 'id',
        'indicator' => 'indicator',
        'lat' => 'lat',
        'line_group' => 'lineGroup',
        'line_mode_groups' => 'lineModeGroups',
        'lines' => 'lines',
        'lon' => 'lon',
        'modes' => 'modes',
        'naptan_id' => 'naptanId',
        'naptan_mode' => 'naptanMode',
        'place_type' => 'placeType',
        'platform_name' => 'platformName',
        'sms_code' => 'smsCode',
        'station_naptan' => 'stationNaptan',
        'status' => 'status',
        'stop_letter' => 'stopLetter',
        'stop_type' => 'stopType',
        'url' => 'url'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'accessibility_summary' => 'setAccessibilitySummary',
        'additional_properties' => 'setAdditionalProperties',
        'children' => 'setChildren',
        'children_urls' => 'setChildrenUrls',
        'common_name' => 'setCommonName',
        'distance' => 'setDistance',
        'full_name' => 'setFullName',
        'hub_naptan_code' => 'setHubNaptanCode',
        'ics_code' => 'setIcsCode',
        'id' => 'setId',
        'indicator' => 'setIndicator',
        'lat' => 'setLat',
        'line_group' => 'setLineGroup',
        'line_mode_groups' => 'setLineModeGroups',
        'lines' => 'setLines',
        'lon' => 'setLon',
        'modes' => 'setModes',
        'naptan_id' => 'setNaptanId',
        'naptan_mode' => 'setNaptanMode',
        'place_type' => 'setPlaceType',
        'platform_name' => 'setPlatformName',
        'sms_code' => 'setSmsCode',
        'station_naptan' => 'setStationNaptan',
        'status' => 'setStatus',
        'stop_letter' => 'setStopLetter',
        'stop_type' => 'setStopType',
        'url' => 'setUrl'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'accessibility_summary' => 'getAccessibilitySummary',
        'additional_properties' => 'getAdditionalProperties',
        'children' => 'getChildren',
        'children_urls' => 'getChildrenUrls',
        'common_name' => 'getCommonName',
        'distance' => 'getDistance',
        'full_name' => 'getFullName',
        'hub_naptan_code' => 'getHubNaptanCode',
        'ics_code' => 'getIcsCode',
        'id' => 'getId',
        'indicator' => 'getIndicator',
        'lat' => 'getLat',
        'line_group' => 'getLineGroup',
        'line_mode_groups' => 'getLineModeGroups',
        'lines' => 'getLines',
        'lon' => 'getLon',
        'modes' => 'getModes',
        'naptan_id' => 'getNaptanId',
        'naptan_mode' => 'getNaptanMode',
        'place_type' => 'getPlaceType',
        'platform_name' => 'getPlatformName',
        'sms_code' => 'getSmsCode',
        'station_naptan' => 'getStationNaptan',
        'status' => 'getStatus',
        'stop_letter' => 'getStopLetter',
        'stop_type' => 'getStopType',
        'url' => 'getUrl'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accessibility_summary'] = isset($data['accessibility_summary']) ? $data['accessibility_summary'] : null;
        $this->container['additional_properties'] = isset($data['additional_properties']) ? $data['additional_properties'] : null;
        $this->container['children'] = isset($data['children']) ? $data['children'] : null;
        $this->container['children_urls'] = isset($data['children_urls']) ? $data['children_urls'] : null;
        $this->container['common_name'] = isset($data['common_name']) ? $data['common_name'] : null;
        $this->container['distance'] = isset($data['distance']) ? $data['distance'] : null;
        $this->container['full_name'] = isset($data['full_name']) ? $data['full_name'] : null;
        $this->container['hub_naptan_code'] = isset($data['hub_naptan_code']) ? $data['hub_naptan_code'] : null;
        $this->container['ics_code'] = isset($data['ics_code']) ? $data['ics_code'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['indicator'] = isset($data['indicator']) ? $data['indicator'] : null;
        $this->container['lat'] = isset($data['lat']) ? $data['lat'] : null;
        $this->container['line_group'] = isset($data['line_group']) ? $data['line_group'] : null;
        $this->container['line_mode_groups'] = isset($data['line_mode_groups']) ? $data['line_mode_groups'] : null;
        $this->container['lines'] = isset($data['lines']) ? $data['lines'] : null;
        $this->container['lon'] = isset($data['lon']) ? $data['lon'] : null;
        $this->container['modes'] = isset($data['modes']) ? $data['modes'] : null;
        $this->container['naptan_id'] = isset($data['naptan_id']) ? $data['naptan_id'] : null;
        $this->container['naptan_mode'] = isset($data['naptan_mode']) ? $data['naptan_mode'] : null;
        $this->container['place_type'] = isset($data['place_type']) ? $data['place_type'] : null;
        $this->container['platform_name'] = isset($data['platform_name']) ? $data['platform_name'] : null;
        $this->container['sms_code'] = isset($data['sms_code']) ? $data['sms_code'] : null;
        $this->container['station_naptan'] = isset($data['station_naptan']) ? $data['station_naptan'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['stop_letter'] = isset($data['stop_letter']) ? $data['stop_letter'] : null;
        $this->container['stop_type'] = isset($data['stop_type']) ? $data['stop_type'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets accessibility_summary
     * @return string
     */
    public function getAccessibilitySummary()
    {
        return $this->container['accessibility_summary'];
    }

    /**
     * Sets accessibility_summary
     * @param string $accessibility_summary
     * @return $this
     */
    public function setAccessibilitySummary($accessibility_summary)
    {
        $this->container['accessibility_summary'] = $accessibility_summary;

        return $this;
    }

    /**
     * Gets additional_properties
     * @return \Abulia\TflUnified\Swagger\Model\AdditionalProperties[]
     */
    public function getAdditionalProperties()
    {
        return $this->container['additional_properties'];
    }

    /**
     * Sets additional_properties
     * @param \Abulia\TflUnified\Swagger\Model\AdditionalProperties[] $additional_properties A bag of additional key/value pairs with extra information about this place.
     * @return $this
     */
    public function setAdditionalProperties($additional_properties)
    {
        $this->container['additional_properties'] = $additional_properties;

        return $this;
    }

    /**
     * Gets children
     * @return \Abulia\TflUnified\Swagger\Model\Place[]
     */
    public function getChildren()
    {
        return $this->container['children'];
    }

    /**
     * Sets children
     * @param \Abulia\TflUnified\Swagger\Model\Place[] $children
     * @return $this
     */
    public function setChildren($children)
    {
        $this->container['children'] = $children;

        return $this;
    }

    /**
     * Gets children_urls
     * @return string[]
     */
    public function getChildrenUrls()
    {
        return $this->container['children_urls'];
    }

    /**
     * Sets children_urls
     * @param string[] $children_urls
     * @return $this
     */
    public function setChildrenUrls($children_urls)
    {
        $this->container['children_urls'] = $children_urls;

        return $this;
    }

    /**
     * Gets common_name
     * @return string
     */
    public function getCommonName()
    {
        return $this->container['common_name'];
    }

    /**
     * Sets common_name
     * @param string $common_name A human readable name.
     * @return $this
     */
    public function setCommonName($common_name)
    {
        $this->container['common_name'] = $common_name;

        return $this;
    }

    /**
     * Gets distance
     * @return double
     */
    public function getDistance()
    {
        return $this->container['distance'];
    }

    /**
     * Sets distance
     * @param double $distance The distance of the place from its search point, if this is the result              of a geographical search, otherwise zero.
     * @return $this
     */
    public function setDistance($distance)
    {
        $this->container['distance'] = $distance;

        return $this;
    }

    /**
     * Gets full_name
     * @return string
     */
    public function getFullName()
    {
        return $this->container['full_name'];
    }

    /**
     * Sets full_name
     * @param string $full_name
     * @return $this
     */
    public function setFullName($full_name)
    {
        $this->container['full_name'] = $full_name;

        return $this;
    }

    /**
     * Gets hub_naptan_code
     * @return string
     */
    public function getHubNaptanCode()
    {
        return $this->container['hub_naptan_code'];
    }

    /**
     * Sets hub_naptan_code
     * @param string $hub_naptan_code
     * @return $this
     */
    public function setHubNaptanCode($hub_naptan_code)
    {
        $this->container['hub_naptan_code'] = $hub_naptan_code;

        return $this;
    }

    /**
     * Gets ics_code
     * @return string
     */
    public function getIcsCode()
    {
        return $this->container['ics_code'];
    }

    /**
     * Sets ics_code
     * @param string $ics_code
     * @return $this
     */
    public function setIcsCode($ics_code)
    {
        $this->container['ics_code'] = $ics_code;

        return $this;
    }

    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id A unique identifier.
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets indicator
     * @return string
     */
    public function getIndicator()
    {
        return $this->container['indicator'];
    }

    /**
     * Sets indicator
     * @param string $indicator The indicator of the stop point e.g. \"Stop K\"
     * @return $this
     */
    public function setIndicator($indicator)
    {
        $this->container['indicator'] = $indicator;

        return $this;
    }

    /**
     * Gets lat
     * @return double
     */
    public function getLat()
    {
        return $this->container['lat'];
    }

    /**
     * Sets lat
     * @param double $lat WGS84 latitude of the location.
     * @return $this
     */
    public function setLat($lat)
    {
        $this->container['lat'] = $lat;

        return $this;
    }

    /**
     * Gets line_group
     * @return \Abulia\TflUnified\Swagger\Model\LineGroup[]
     */
    public function getLineGroup()
    {
        return $this->container['line_group'];
    }

    /**
     * Sets line_group
     * @param \Abulia\TflUnified\Swagger\Model\LineGroup[] $line_group
     * @return $this
     */
    public function setLineGroup($line_group)
    {
        $this->container['line_group'] = $line_group;

        return $this;
    }

    /**
     * Gets line_mode_groups
     * @return \Abulia\TflUnified\Swagger\Model\LineModeGroup[]
     */
    public function getLineModeGroups()
    {
        return $this->container['line_mode_groups'];
    }

    /**
     * Sets line_mode_groups
     * @param \Abulia\TflUnified\Swagger\Model\LineModeGroup[] $line_mode_groups
     * @return $this
     */
    public function setLineModeGroups($line_mode_groups)
    {
        $this->container['line_mode_groups'] = $line_mode_groups;

        return $this;
    }

    /**
     * Gets lines
     * @return \Abulia\TflUnified\Swagger\Model\Identifier[]
     */
    public function getLines()
    {
        return $this->container['lines'];
    }

    /**
     * Sets lines
     * @param \Abulia\TflUnified\Swagger\Model\Identifier[] $lines
     * @return $this
     */
    public function setLines($lines)
    {
        $this->container['lines'] = $lines;

        return $this;
    }

    /**
     * Gets lon
     * @return double
     */
    public function getLon()
    {
        return $this->container['lon'];
    }

    /**
     * Sets lon
     * @param double $lon WGS84 longitude of the location.
     * @return $this
     */
    public function setLon($lon)
    {
        $this->container['lon'] = $lon;

        return $this;
    }

    /**
     * Gets modes
     * @return string[]
     */
    public function getModes()
    {
        return $this->container['modes'];
    }

    /**
     * Sets modes
     * @param string[] $modes
     * @return $this
     */
    public function setModes($modes)
    {
        $this->container['modes'] = $modes;

        return $this;
    }

    /**
     * Gets naptan_id
     * @return string
     */
    public function getNaptanId()
    {
        return $this->container['naptan_id'];
    }

    /**
     * Sets naptan_id
     * @param string $naptan_id
     * @return $this
     */
    public function setNaptanId($naptan_id)
    {
        $this->container['naptan_id'] = $naptan_id;

        return $this;
    }

    /**
     * Gets naptan_mode
     * @return string
     */
    public function getNaptanMode()
    {
        return $this->container['naptan_mode'];
    }

    /**
     * Sets naptan_mode
     * @param string $naptan_mode
     * @return $this
     */
    public function setNaptanMode($naptan_mode)
    {
        $this->container['naptan_mode'] = $naptan_mode;

        return $this;
    }

    /**
     * Gets place_type
     * @return string
     */
    public function getPlaceType()
    {
        return $this->container['place_type'];
    }

    /**
     * Sets place_type
     * @param string $place_type The type of Place. See /Place/Meta/placeTypes for possible values.
     * @return $this
     */
    public function setPlaceType($place_type)
    {
        $this->container['place_type'] = $place_type;

        return $this;
    }

    /**
     * Gets platform_name
     * @return string
     */
    public function getPlatformName()
    {
        return $this->container['platform_name'];
    }

    /**
     * Sets platform_name
     * @param string $platform_name
     * @return $this
     */
    public function setPlatformName($platform_name)
    {
        $this->container['platform_name'] = $platform_name;

        return $this;
    }

    /**
     * Gets sms_code
     * @return string
     */
    public function getSmsCode()
    {
        return $this->container['sms_code'];
    }

    /**
     * Sets sms_code
     * @param string $sms_code
     * @return $this
     */
    public function setSmsCode($sms_code)
    {
        $this->container['sms_code'] = $sms_code;

        return $this;
    }

    /**
     * Gets station_naptan
     * @return string
     */
    public function getStationNaptan()
    {
        return $this->container['station_naptan'];
    }

    /**
     * Sets station_naptan
     * @param string $station_naptan
     * @return $this
     */
    public function setStationNaptan($station_naptan)
    {
        $this->container['station_naptan'] = $station_naptan;

        return $this;
    }

    /**
     * Gets status
     * @return bool
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     * @param bool $status
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets stop_letter
     * @return string
     */
    public function getStopLetter()
    {
        return $this->container['stop_letter'];
    }

    /**
     * Sets stop_letter
     * @param string $stop_letter The stop letter, if it could be cleansed from the Indicator e.g. \"K\"
     * @return $this
     */
    public function setStopLetter($stop_letter)
    {
        $this->container['stop_letter'] = $stop_letter;

        return $this;
    }

    /**
     * Gets stop_type
     * @return string
     */
    public function getStopType()
    {
        return $this->container['stop_type'];
    }

    /**
     * Sets stop_type
     * @param string $stop_type
     * @return $this
     */
    public function setStopType($stop_type)
    {
        $this->container['stop_type'] = $stop_type;

        return $this;
    }

    /**
     * Gets url
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     * @param string $url The unique location of this resource.
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * To allow implict conversion to JSON by Laravel.
     */
    public function toJson($options = 0)
    {
        return $this->__toString();
    }

    /**
     * For convenient property based access.
     */
    public function __get($name)
    {
        if (isset(static::$getters[$name])) {
            return $this->{static::$getters[$name]}();
        }
        return null;
    }
}


