<?php
/**
 * StreetSegment
 *
 * PHP version 5
 *
 * @category Class
 * @package  Abulia\TflUnified\Swagger
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transport for London Unified API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Abulia\TflUnified\Swagger\Model;

use \ArrayAccess;
use Illuminate\Contracts\Support\Jsonable;

/**
 * StreetSegment Class Doc Comment
 *
 * @category    Class
 * @package     Abulia\TflUnified\Swagger
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StreetSegment implements ArrayAccess, Jsonable
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'StreetSegment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'line_string' => 'string',
        'source_system_id' => 'int',
        'source_system_key' => 'string',
        'toid' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'line_string' => 'lineString',
        'source_system_id' => 'sourceSystemId',
        'source_system_key' => 'sourceSystemKey',
        'toid' => 'toid'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'line_string' => 'setLineString',
        'source_system_id' => 'setSourceSystemId',
        'source_system_key' => 'setSourceSystemKey',
        'toid' => 'setToid'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'line_string' => 'getLineString',
        'source_system_id' => 'getSourceSystemId',
        'source_system_key' => 'getSourceSystemKey',
        'toid' => 'getToid'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['line_string'] = isset($data['line_string']) ? $data['line_string'] : null;
        $this->container['source_system_id'] = isset($data['source_system_id']) ? $data['source_system_id'] : null;
        $this->container['source_system_key'] = isset($data['source_system_key']) ? $data['source_system_key'] : null;
        $this->container['toid'] = isset($data['toid']) ? $data['toid'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets line_string
     * @return string
     */
    public function getLineString()
    {
        return $this->container['line_string'];
    }

    /**
     * Sets line_string
     * @param string $line_string geoJSON formatted LineString containing two latitude/longitude (WGS84) pairs that identify the start and end points of the street segment.
     * @return $this
     */
    public function setLineString($line_string)
    {
        $this->container['line_string'] = $line_string;

        return $this;
    }

    /**
     * Gets source_system_id
     * @return int
     */
    public function getSourceSystemId()
    {
        return $this->container['source_system_id'];
    }

    /**
     * Sets source_system_id
     * @param int $source_system_id The ID from the source system of the disruption that this street belongs to.
     * @return $this
     */
    public function setSourceSystemId($source_system_id)
    {
        $this->container['source_system_id'] = $source_system_id;

        return $this;
    }

    /**
     * Gets source_system_key
     * @return string
     */
    public function getSourceSystemKey()
    {
        return $this->container['source_system_key'];
    }

    /**
     * Sets source_system_key
     * @param string $source_system_key The key of the source system of the disruption that this street belongs to.
     * @return $this
     */
    public function setSourceSystemKey($source_system_key)
    {
        $this->container['source_system_key'] = $source_system_key;

        return $this;
    }

    /**
     * Gets toid
     * @return string
     */
    public function getToid()
    {
        return $this->container['toid'];
    }

    /**
     * Sets toid
     * @param string $toid A 16 digit unique integer identifying a OS ITN (Ordnance Survey Integrated Transport Network) road link.
     * @return $this
     */
    public function setToid($toid)
    {
        $this->container['toid'] = $toid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Abulia\TflUnified\Swagger\ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * To allow implict conversion to JSON by Laravel.
     */
    public function toJson($options = 0)
    {
        return $this->__toString();
    }

    /**
     * For convenient property based access.
     */
    public function __get($name)
    {
        if (isset(static::$getters[$name])) {
            return $this->{static::$getters[$name]}();
        }
        return null;
    }
}


